[versions]
androidx-core = "1.9.0"
lifecycle-runtime-ktx = "2.5.1"
material = "1.3.1"
activity-compose = "1.6.1"
compose = "1.3.3"
compose-view-model = "2.5.1"
android-junit = "1.1.5"
junit = "4.13.2"
espresso-core = "3.5.1"
hilt = "2.44"
coil = "2.2.2"
navigation-compose = "2.5.3"
hilt-navigation-compose = "1.0.0"
javax-inject = "1"
room = "2.5.0"
coroutine-core = "1.6.4"
navigation-animation-compose = "0.29.1-alpha"

[libraries]
androidx-core = { module = "androidx.core:core-ktx", version.ref = "androidx-core"}
lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle-runtime-ktx"}
material-compose = { module = "androidx.compose.material:material", version.ref = "material"}
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose"}
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose"}
compose-ui-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose"}
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose"}
compose-ui-test = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "compose"}
test-junit = { module = "androidx.test.ext:junit", version.ref = "android-junit" }
test-espresso = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso-core" }
compose-test-junit = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose" }
junit = { module = "junit:junit", version.ref = "junit" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }
compose-view-model = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "compose-view-model"}
coil-core = { module = "io.coil-kt:coil", version.ref = "coil" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
coil-svg = { module = "io.coil-kt:coil-svg", version.ref = "coil" }
navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation-compose" }
hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hilt-navigation-compose" }
javax-inject = { module = "javax.inject:javax.inject", version.ref = "javax-inject" }
room-core = { module = "androidx.room:room-runtime", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutine-core" }
navigation-animation-compose = { module = "com.google.accompanist:accompanist-navigation-animation", version.ref = "navigation-animation-compose" }

[bundles]
compose-core = ["compose-ui", "compose-ui-preview", "activity-compose", "compose-view-model", "navigation-animation-compose"]
android-core = ["androidx-core", "lifecycle-runtime-ktx"]
material = ["material-compose"]
android-test = ["test-junit", "test-espresso"]
compose-test = ["compose-ui-tooling", "compose-ui-test"]
coil = ["coil-core", "coil-compose", "coil-svg"]
navigation = ["navigation-compose", "hilt-navigation-compose"]
room = ["room-core", "room-ktx"]

[plugins]
android-app = { id = "com.android.application", version = "'7.4.1'"}